# Generated by Django 4.2.2 on 2023-06-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='produc_name',
            new_name='product_name',
        ),
    ]
