# Generated by Django 4.2.2 on 2023-06-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
