# Generated by Django 4.2.2 on 2023-06-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_rename_data_added_cart_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date_added',
            new_name='data_added',
        ),
    ]
