# Generated by Django 4.2.2 on 2023-06-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_rename_date_added_cart_data_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
